---
- name: Create temp directory
  file: path={{playbook_dir}}/tmp state=directory

- name: Unzip CH340 Driver
  unarchive: src={{item}} dest={{playbook_dir}}/tmp
  with_fileglob: files/*.zip

- name: Install PKG
  command: installer -package {{item}} -target /
  become: True
  with_fileglob: "{{playbook_dir}}/tmp/*.pkg"

- name: Clean up
  become: True
  file: path={{playbook_dir}}/tmp state=absent
